export const TrackingStatus = {
    new_created: "NEW_CREATED",
    reject: "REJECT",
    confirmed: "CONFIRMED",
    assigned_hub_to_pick: "ASSIGNED_HUB_TO_PICK",
    qr_generated: "QR_GENERATED",
    label_generated: "LABEL_GENERATED",
    pickup_assigned: "PICKUP_ASSIGNED",
    out_for_pickup: "OUT_FOR_PICKUP",
    order_picked: "ORDER_PICKED",
    at_hub: "AT_HUB",
    order_bagged: "ORDER_BAGGED",
    carrier_assigned: "CARRIER_ASSIGNED",
    carrier_delivery_agent_assigned: "CARRIER_DELIVERY_AGENT_ASSIGNED",
    delivered_to_carrier: "DELIVERED_TO_CARRIER",
    carrier_received: "CARRIER_RECEIVED",
    in_transit: "IN_TRANSIT",
    delivery_agent_assigned: "DELIVERY_AGENT_ASSIGNED",
    out_for_delivery: "OUT_FOR_DELIVERY",
    order_delivered: "ORDER_DELIVERED",
}
